app_key: <%= ENV["TCC_DROPBOX_APP_KEY"] %>
app_secret: <%= ENV["TCC_DROPBOX_APP_SECRET"] %>
access_token: <%= ENV["TCC_DROPBOX_ACCESS_TOKEN"] %>
access_token_secret: <%= ENV["TCC_DROPBOX_TOKEN_SECRET"] %>
user_id: <%= ENV["TCC_DROPBOX_USER_ID"] %>
access_type: "app_folder"
